### ISSUE TITLE
Unique "key" prop for Select

### ISSUE THREAD

**Issue by girafic** [alexandrtovmach/react-figma-plugin-ds#12]
I get the notification "Warning: Each child in a list should have a unique "key" prop. Check the render method of `Select` in the console. Already checked that the "key" prop are in  li tag. Do you've some information how to solve that?

**Comment by alexandrtovmach** [comment]
@girafic Thanks for reporting! Yeah, seems like I missed that, will fix soon

**Comment by alexandrtovmach** [comment]
Fix released in [v2.0.5](https://www.npmjs.com/package/react-figma-plugin-ds/v/2.0.3)
