### ISSUE TITLE
Commit package-lock.json/yarn.lock

### ISSUE THREAD

**Issue by Klemensas** [alexandrtovmach/react-figma-plugin-ds#15]
Why are lock files in the ignore list?

Ideally, these files should be committed, [see here for more details](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)

**Comment by Klemensas** [comment]
The same goes for styles, what's the benefit of omitting them from the repo?
This disables installing the package directly from the repo :(

**Comment by alexandrtovmach** [comment]
thanks for reporting 👍 yes, you right, fixed in 2.2.0
