### ISSUE TITLE
Update React peer dependencies

### ISSUE THREAD

**Issue by romannurik** [alexandrtovmach/react-figma-plugin-ds#20]
This repo currently requires exactly version 16.3.0 of react and react-dom. Would be good to switch it to e.g. `^16.3.0` to allow newer versions?

**Comment by alexandrtovmach** [comment]
Sounds reasonable 👍

**Comment by alexandrtovmach** [comment]
fixed in v2.2.0

**Comment by romannurik** [comment]
Thanks for the fast response!
