### ISSUE TITLE
Allow controlled components

### ISSUE THREAD

**Issue by lukasoppermann** [alexandrtovmach/react-figma-plugin-ds#26]
As outlined in #25 to display settings loaded from local storage it is necessary to work with controlled components (this is also the recommended react way: https://reactjs.org/docs/uncontrolled-components.html)

It could be great to allow users to choose by adding value to select and input, checked to checkboxes, ...

**Comment by alexandrtovmach** [comment]
I'm thinking about allowing this in next version, like v3, but not as patch to current one. It's something that will be a braking change (I also would like to allow to pass all supported native props down to component). So I thinking about it, but not sure when I'll have a time to work on it

**Comment by lukasoppermann** [comment]
What do you think about starting a v3 branch so that for those of us who need controlled components, there is a way of already getting them?

**Comment by shnydercom** [comment]
> I'm thinking about allowing this in next version, like v3, but not as patch to current one. It's something that will be a braking change (I also would like to allow to pass all supported native props down to component). So I thinking about it, but not sure when I'll have a time to work on it

@alexandrtovmach could you have a look at this PR, which does exactly that (passing native props to the components) https://github.com/alexandrtovmach/react-figma-plugin-ds/pull/42

**Comment by lukasoppermann** [comment]
Stale repo?
